### ISSUE TITLE
Discord link does not work

### ISSUE THREAD

**Issue by Musa-Sina-Ertugrul** [google/temporian#366]
I wanted to join discord to contribute but, I could not. Can you regenerate link ? 
![image](https://github.com/google/temporian/assets/102359522/a822adca-9679-4f1a-9c31-6b4fe7dbfd5b)

**Comment by ianspektor** [comment]
Thanks for the heads up @Musa-Sina-Ertugrul! Link has been updated in README and docs: https://discord.gg/nT54yATCTy
