### ISSUE TITLE
Support timezone argument in calendar operators

### ISSUE THREAD

**Issue by ianspektor** [google/temporian#38]
[see complete conversation in comment thread in original PR]

TLDR: we want to support a `tz` argument for the calendar operators, but the `tz` arg received by `datetime.fromtimestamp` is an instance of a class instead of a string

_Originally posted by @ianspektor in https://github.com/google/temporian/pull/31#discussion_r1140306183_

**Comment by rstz** [comment]
Moved to roadmap
