### ISSUE TITLE
New operator: moving_product

### ISSUE THREAD

**Issue by ianspektor** [google/temporian#380]
New `EventSet.moving_product()` operator.

See `EventSet.moving_sum()` for reference. Note that this issue will require C++ code.

See https://github.com/google/temporian/blob/main/CONTRIBUTING.md#developing-a-new-operator for guidance.

Questions or requests for additional guidance from possible contributors more than welcome!

**Comment by akshatvishu** [comment]
Will be working on this as a part of #350

**Comment by ianspektor** [comment]
Hey @akshatvishu!

This involves modifying quite a bit of cpp code:
- Creating a new `Accumulator` implementation (see `MovingSumAccumulator` in `temporian/implementation/numpy_cc/operators/window.cc`)
- Creating new `accumulate` overloads for moving_product in the same file
- Registering and creating bindings for the new accumulate cpp functions (see bottom of that same file)

Plus, there's some specifics to moving product that make it not as straightforward to implement as  moving sum, for example. We'd rather have the core dev team implement this (ETA: this/next week tops) and then have you do cumprod alone - unless you are perfectly comfortable with all of the above, in which case I can give more detail as to what these specifics are and let you take a shot at it :)

Let me know!

**Comment by ianspektor** [comment]
Sounds great 👍🏼 and great questions.

- Zero or extreme values: zeros will result in the accumulator's result being 0. NaNs should be ignored (i.e., if we have a `[2, NaN, 3]` window, the result should still be 6, not NaN).
- Accumulate overloads: you don't need to modify these, you'll just need to add the `REGISTER_CC_FUNC` and `ADD_PY_DEF` calls. See `simple_moving_average`'s for reference.

Some extra notes:
- You'll see that most accumulators work by adding/removing the new/old values from the window directly onto the accumulation result. This won't be possible here, since `0` would erase the accumulation, and precision loss would be high. Instead, we want the accumulator to store the left/right indexes, and compute the product on the whole window in `Result()`.
- No need to raise an error message on overflow ([numpy doesn't in cumprod](https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html))
- We'll only make this available for float types for now. This restriction should be in the C defs, the operator's accepted types, and the function's docstring.
- Please do `moving_product` only for this task, leave `cumprod` for a follow up.

Issue and discord always open 💪🏼
