### ISSUE TITLE
Convert methods to `property` where appropiate

### ISSUE THREAD

**Issue by ianspektor** [google/temporian#46]
Methods with no arguments that just return a value from the class' internal state should be made properties via the `@property` decorator. This makes the syntax cleaner when calling the getter and makes it clear that the method is just returning one of the class' values.

We can additionally use the `@property.setter` where applicable.

Examples:
- core sampling: index, creator, set_creator
- core feature: name, dtype, sampling, creator, set_sampling, set_creator
etc.

**Comment by diegomarvid** [comment]
Agree, `schema()` should be a property as well

**Comment by ianspektor** [comment]
> schema() should be a property as well
not too sure about that, since it's creating and returning a new object
